server:
  port: 9903

spring:
  config:
    use-legacy-processing: true
  application:
    name: read-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 30
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
    registry-fetch-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 1
#    prefer-ip-address: true


