server:
  port: 9901

spring:
  application:
    name: book-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:9001/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}

